#!/usr/bin/env python3
"""Generate every arm's config from ONE definition.

The arms must be identical except for the memory switch. Four hand-written
jsonnet files cannot promise that -- one edited temperature or max_steps in
one of them silently confounds the whole comparison -- so they are generated
from a single base here, and the only per-arm keys are the memory ones.

    python3 make_configs.py --root ~/mg/local/appworld --workdir ~/mg/local/areev-runs/appworld/run1

Emits, under `<root>/experiments/configs/`:

    areev/<arm>/<model>/<dataset>.jsonnet

for the learn pass (`train`) and every held-out pass (`test_normal`).
"""
from __future__ import annotations

import argparse
import json
import os

MODEL_SLUG = "qwen/qwen3-30b-a3b-instruct-2507"
MODEL_DIR = "qwen3-30b-a3b-instruct-2507_openrouter"

# OpenRouter's StreamLake endpoint, quoted 2026-09-08. These are the rates
# actually billed because `run_experiment.py --provider` pins that upstream.
COST_PER_TOKEN = {
    "input_cache_hit": 4.815e-08,
    "input_cache_miss": 4.815e-08,
    "input_cache_write": 0.0,
    "output": 1.9305e-07,
}

PROMPT_PLACEHOLDER = "@@PROMPT@@"


def base_agent(max_cost_overall: float, max_cost_per_task: float) -> dict:
    """Everything the arms share. Touch this and every arm moves together."""
    return {
        "type": "areev_react_code_agent",
        "model_config": {
            "client_name": "openai",
            "api_type": "chat_completions",
            "base_url": "https://openrouter.ai/api/v1",
            "api_key_env_name": "OPENROUTER_API_KEY",
            "name": MODEL_SLUG,
            "temperature": 0.0,
            "seed": 100,
            "drop_reasoning_content": False,
            "cost_per_token": COST_PER_TOKEN,
            "retry_after_n_seconds": 15,
            "use_cache": False,
            "max_retries": 20,
        },
        "appworld_config": {"random_seed": 100, "raise_on_extra_parameters": True},
        "logger_config": {"color": False, "verbose": True},
        "usage_tracker_config": {
            "max_cost_overall": max_cost_overall,
            "max_cost_per_task": max_cost_per_task,
            "max_output_tokens_per_task": 100000,
        },
        "prompt_file_path": PROMPT_PLACEHOLDER,
        "ignore_multiple_calls": True,
        "max_prompt_length": None,
        "max_output_length": None,
        "max_steps": 50,
        "log_lm_calls": True,
        "skip_if_finished": True,
    }


def render(agent: dict, dataset: str, arm: str) -> str:
    body = json.dumps(
        {
            "type": "simplified",
            "config": {"agent": agent, "dataset": dataset},
            "metadata": {
                "model": {
                    "file_name": MODEL_DIR,
                    "humanized_name": "Qwen3 30B A3B Instruct 2507",
                    "precise_name": MODEL_SLUG,
                    "creator": "alibaba",
                    "provider": "openrouter",
                },
                "agent": {
                    "file_name": "areev_react_code_agent",
                    "humanized_name": "Areev ReAct Code Agent (%s)" % arm,
                },
            },
        },
        indent=4,
    )
    # jsonnet is a superset of JSON; only the prompt path needs computing.
    body = body.replace(
        '"%s"' % PROMPT_PLACEHOLDER,
        'experiment_prompts_path + "/react_code_agent/instructions.txt"',
    )
    header = (
        "// GENERATED by make_configs.py -- do not edit by hand.\n"
        "// Every arm is emitted from one base so that the only difference\n"
        "// between them is the memory switch.\n"
        'local experiment_prompts_path = std.extVar("APPWORLD_EXPERIMENT_PROMPTS_PATH");\n'
    )
    return header + body + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True)
    ap.add_argument("--workdir", required=True, help="where the arms' memories live")
    ap.add_argument("--learn-dataset", default="train")
    ap.add_argument("--eval-dataset", default="test_normal")
    ap.add_argument("--max-cost-overall", type=float, default=8.0)
    ap.add_argument("--max-cost-per-task", type=float, default=0.5)
    ap.add_argument("--learn-every", type=int, default=1)
    ap.add_argument("--loop-llm-cmd", default=os.environ.get("AREEV_LOOP_LLM_CMD", ""))
    ap.add_argument("--loop-ground-cmd", default=os.environ.get("AREEV_LOOP_GROUND_CMD", ""))
    ap.add_argument("--review-cmd", default=os.environ.get("AREEV_REVIEW_CMD", ""))
    args = ap.parse_args()

    root = os.path.expanduser(args.root)
    workdir = os.path.expanduser(args.workdir)
    configs_dir = os.path.join(root, "experiments", "configs")
    if not os.path.isdir(configs_dir):
        raise SystemExit(f"not an AppWorld root: {root}")

    def db(arm: str, phase: str) -> str:
        return os.path.join(workdir, arm, f"{phase}.db")

    # (arm directory, dataset, memory kwargs)
    plan: list[tuple[str, str, dict]] = [
        # -- the learn pass: memory is built here, on train only --------------
        ("learn-passive", args.learn_dataset,
         {"memory_mode": "passive", "memory_db": db("passive", "learn"), "learn_every": 0}),
        ("learn-governed", args.learn_dataset,
         {"memory_mode": "governed", "memory_db": db("governed", "learn"),
          "learn_every": args.learn_every, "loop_llm_cmd": args.loop_llm_cmd or None,
          "loop_ground_cmd": args.loop_ground_cmd or None,
          "review_cmd": args.review_cmd or None}),
        # -- the held-out arms: every memory FROZEN (learn_every 0) -----------
        ("arm-a-none", args.eval_dataset, {"memory_mode": "none"}),
        ("arm-b-passive", args.eval_dataset,
         {"memory_mode": "passive", "memory_db": db("passive", "eval"),
          "memory_frozen": True, "learn_every": 0}),
        # B2 is a second identical pass of B against the same frozen memory.
        # It is the noise floor, and it is a separate experiment name only so
        # that its outputs do not overwrite B's.
        ("arm-b2-passive", args.eval_dataset,
         {"memory_mode": "passive", "memory_db": db("passive", "eval"),
          "memory_frozen": True, "learn_every": 0}),
        ("arm-c-governed", args.eval_dataset,
         {"memory_mode": "governed", "memory_db": db("governed", "eval"),
          "memory_frozen": True, "learn_every": 0}),
    ]

    written = []
    for arm, dataset, memory_kwargs in plan:
        agent = base_agent(args.max_cost_overall, args.max_cost_per_task)
        agent.update({k: v for k, v in memory_kwargs.items() if v is not None})
        out_dir = os.path.join(configs_dir, "areev", arm, MODEL_DIR)
        os.makedirs(out_dir, exist_ok=True)
        path = os.path.join(out_dir, f"{dataset}.jsonnet")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(render(agent, dataset, arm))
        written.append(f"areev/{arm}/{MODEL_DIR}/{dataset}")

    print("wrote %d configs under %s:" % (len(written), configs_dir))
    for name in written:
        print("  " + name)
    print("\nmemories live under %s" % workdir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
