[package]
name = "areev-tool-rest-poll"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lib]
name = "areev_tool_rest_poll"
crate-type = ["cdylib"]

[dependencies]
areev-tool-common = { path = "../common" }

[package.metadata.areev]
tool = "rest.poll"
